### ISSUE TITLE
Singleplayer

### ISSUE THREAD

**Issue by Python-Sargent** [EISHU-MT/cs_mt#1]
It says in the description that it can do singleplayer, but I can't find out how to enable it.

How does it work?

**Comment by EISHU92** [comment]
Im sorry, the singleplayer mode will be available soon
Enabling bots, next update it will be fixed to play with bots.

**Comment by Python-Sargent** [comment]
You are working hard, you just started June 9th! Pretty good game already.

**Comment by Python-Sargent** [comment]
Not to stray off-topic, but how do you publish maps?

**Comment by Python-Sargent** [comment]
Could you use the mobs API and make the bots a monster you spawn at the starting point?

**Comment by EISHU92** [comment]
**Maps Editing**: CS:MT Has already a tool for managing MTS files, to enable map making, follow those steps:

- Make a new world (non-singlenode mapgen)
- Go to minetest settings and search cs_map, and enable map_maker
- Join in the world (If all done) and build the map. In the wiki are all info for it.

**Comment by Python-Sargent** [comment]
![image](https://github.com/EISHU-MT/cs_mt/assets/90115230/598816fa-350a-4664-8af4-478a4b975d55)

I couldn't help noticing the similarity, it's as if you were trying.
