### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by Python-Sargent** [EISHU-MT/cs_mt#2]
I saw the server up two days ago, but I can't find it now, is it a temporary or a non-global server?

**Comment by EISHU92** [comment]
The server sometimes is down by technical problems

**Comment by Python-Sargent** [comment]
The server is back up, but how come I'm stuck in the slope wall at start?

**Comment by Python-Sargent** [comment]
I killed the server, I tried to pick up the bomb, and I pretty sure I was a counter, instant crash.

**Comment by Python-Sargent** [comment]
can't repro.

**Comment by EISHU92** [comment]
repro?
