### ISSUE TITLE
Translation (esp. prompts and hints)

### ISSUE THREAD

**Issue by Python-Sargent** [EISHU-MT/cs_mt#4]
Your translations can be a little hard to understand, they also contain words that are no longer used in the general public such as 'goodly'.

I would be more than happy to help with translations if you want, otherwise, you may wish to contact someone who can rewrite the translations.

**Comment by EISHU92** [comment]
Yeah, you can help with it :)

**Comment by Python-Sargent** [comment]
Ok. I'll get started right now.
