### ISSUE TITLE
Bots incompatability

### ISSUE THREAD

**Issue by Python-Sargent** [EISHU-MT/cs_mt#7]
A small bug:

`AsyncErr: Lua: Runtime error from mod 'cs_core' in callback on_joinplayer(): ...in64\bin\..\games\csgo_mt\mods\cs_core\cs_tools\init.lua:17: attempt to call field 'is_bot' (a nil value)
stack traceback:
	...in64\bin\..\games\csgo_mt\mods\cs_core\cs_tools\init.lua:17: in function 'Name'
	...in64\bin\..\games\csgo_mt\mods\cs_core\cs_tools\init.lua:64: in function 'AddPrivs'
	...in64\bin\..\games\csgo_mt\mods\cs_core\cs_core/core1.lua:57: in function <...in64\bin\..\games\csgo_mt\mods\cs_core\cs_core/core1.lua:51>
	...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:446: in function <...st\minetest-5.7.0-win64\bin\..\builtin\game\register.lua:432>`

**Comment by EISHU92** [comment]
Thank you! Now it is fixed
